#' @title Generate alternative text from a ggplot2 object
#'
#' @description
#' `generate_alt_text()` takes any ggplot2 object and generates
#' a string that describes what contains the chart.
#'
#' The description isn't meant to exactly describe the chart,
#' nor how it was made. Instead, it tries to be short and
#' gives an overview of what's inside the chart such as:
#' - the kind of chart(s)
#' - the number of chart(s) for facets
#' - the title
#' - ...
#'
#' The text can be generated in: English (default), French or
#' German.
#'
#' Learn more: https://www.section508.gov/create/alternative-text/
#'
#' @param p A `ggplot` object.
#' @param ... Ignored.
#' @param lang Language used for generated text. Defaults to `"en"` (English).
#'     Supported values are `"en"`, `"fr"` (French), and `"de"` (German).
#' @param include_title Whether to include the title of the plot, if any, in the
#'     alternative text. This is mostly useful to reduce the length of the text.
#' @param max_character The maximum number of characters allowed (default to 125 as
#'     recommended by most references). If above, it will raise a warning. If
#'     `stop_on_max_character = TRUE`, then it will raise an error.
#' @param stop_on_max_character Whether to raise an error when the number of
#'     characters of the alt text is above `max_character`. If `FALSE`, it will
#'     raise a warning.
#' @param from Method used to select alt text. Since ggplot2 objects can
#'     include built-in alt text (via `labs(alt = "Here goes the text")`),
#'     choose whether to use that text or the one generated by `ggalttext`.
#'     - `"default"`: always generate alt text with `ggalttext`.
#'     - `"auto"`: use existing alt text when it is non-empty; otherwise generate
#'       alt text with `ggalttext`.
#'     - `"origin"`: always return `ggplot2::get_alt_text(p)` as-is.
#'
#' @return A string
#'
#' @export
generate_alt_text <- function(
    p,
    ...,
    lang = "en",
    include_title = TRUE,
    max_character = 125,
    stop_on_max_character = FALSE,
    from = c("default", "auto", "origin")
) {
    if (!inherits(p, "ggplot")) {
        cls <- paste(class(p), collapse = ", ")
        stop(
            "Object is not a valid ggplot2 object: '",
            cls,
            "'.",
            call. = FALSE
        )
    }

    if (length(list(...)) > 0) {
        stop("All arguments (except p, the plot) must be named.")
    }

    from <- match.arg(from)
    lang <- match_language(lang)

    if (from == "auto") {
        origin_alt_text <- ggplot2::get_alt_text(p)
        if (!is.na(origin_alt_text) && nzchar(origin_alt_text)) {
            return(origin_alt_text)
        }
    } else if (from == "origin") {
        return(ggplot2::get_alt_text(p))
    }

    p_main <- resolve_plot_for_alt(p)
    b <- ggplot2::ggplot_build(p_main)

    chart_sentence <- describe_chart_type_sentence(p_main, lang = lang)
    chart_sentence <- append_data_type(
        chart_sentence,
        p_main,
        b,
        lang = lang
    )
    chart <- sub("[.]$", "", chart_sentence)
    panel_sentence <- describe_panel_layout_sentence(
        b,
        chart = chart,
        lang = lang
    )
    opening_sentence <- if (nzchar(panel_sentence)) {
        panel_sentence
    } else {
        chart_sentence
    }
    opening_sentence <- append_plot_title(
        opening_sentence,
        p_main,
        lang = lang,
        include_title = include_title
    )

    pieces <- c(
        opening_sentence,
        describe_discrete_scales_sentence(b, lang = lang)
    )

    alt_text <- paste(pieces[nzchar(pieces)], collapse = " ")

    if (nchar(alt_text) > max_character) {
        mess <- paste0(
            "Alternative text is more than ",
            max_character,
            " characters (",
            nchar(alt_text),
            "). ",
            "This is above what's considered best for alt texts. ",
            "Consider making it shorter with `include_title = FALSE` or ",
            "increase this threshold with the `max_character` argument."
        )
        if (stop_on_max_character) {
            stop(mess)
        } else {
            warning(mess)
        }
    }

    return(alt_text)
}

#' @keywords internal
resolve_plot_for_alt <- function(p) {
    if (!inherits(p, "patchwork")) {
        return(p)
    }

    plots <- p$patches$plots
    if (!length(plots)) {
        return(p)
    }

    candidate <- plots[[1]]
    if (!inherits(candidate, "ggplot")) {
        return(p)
    }

    resolve_plot_for_alt(candidate)
}
