#' @title Generate alternative text from a ggplot2 object
#'
#' @description
#' `generate_alt_text()` takes any ggplot2 object and generates
#' a string that describes what contains the chart.
#'
#' The description isn't meant to exactly describe the chart,
#' nor how it was made. Instead, it tries to be short and
#' gives an overview of what's inside the chart such as:
#' - the kind of chart(s)
#' - the number of chart(s) for facets
#' - the title, subtitle and caption
#'
#' Learn more: https://www.section508.gov/create/alternative-text/
#'
#' @param p A `ggplot` object.
#' @param ... Ignored.
#' @param from Method used to select alt text. Since ggplot2 objects can
#'     include built-in alt text (via `labs(alt = "Here goes the text")`),
#'     choose whether to use that text or the one generated by `ggalttext`.
#'     - `"default"`: always generate alt text with `ggalttext`.
#'     - `"auto"`: use existing alt text when it is non-empty; otherwise generate
#'       alt text with `ggalttext`.
#'     - `"origin"`: always return `ggplot2::get_alt_text(p)` as-is.
#' @param lang Language used for generated text. Defaults to `"en"` (English).
#'     Supported values are `"en"`, `"fr"` (French), and `"de"` (German).
#' @param include_title Whether to include the title of the plot, if any, in the
#'     alternative text.
#'
#' @return A string
#'
#' @export
generate_alt_text <- function(
    p,
    ...,
    from = c("default", "auto", "origin"),
    lang = "en",
    include_title = TRUE
) {
    if (!inherits(p, "ggplot")) {
        cls <- paste(class(p), collapse = ", ")
        stop(
            "Object is not a valid ggplot2 object: '",
            cls,
            "'.",
            call. = FALSE
        )
    }

    if (length(list(...)) > 0) {
        stop("All arguments (except p, the plot) must be named.")
    }

    from <- match.arg(from)
    lang <- match_language(lang)

    if (from == "auto") {
        origin_alt_text <- ggplot2::get_alt_text(p)
        if (!is.na(origin_alt_text) && nzchar(origin_alt_text)) {
            return(origin_alt_text)
        }
    } else if (from == "origin") {
        return(ggplot2::get_alt_text(p))
    }

    p_main <- resolve_plot_for_alt(p)
    b <- ggplot2::ggplot_build(p_main)

    pieces <- c(
        describe_chart_type_sentence(p_main, lang = lang),
        describe_panel_layout_sentence(b, lang = lang),
        describe_facet_values_sentence(b, lang = lang),
        describe_discrete_scales_sentence(b, lang = lang),
        describe_plot_labels_sentences(
            p_main,
            lang = lang,
            include_title = include_title
        )
    )

    paste(pieces[nzchar(pieces)], collapse = " ")
}

#' @keywords internal
resolve_plot_for_alt <- function(p) {
    if (!inherits(p, "patchwork")) {
        return(p)
    }

    plots <- p$patches$plots
    if (!length(plots)) {
        return(p)
    }

    candidate <- plots[[1]]
    if (!inherits(candidate, "ggplot")) {
        return(p)
    }

    resolve_plot_for_alt(candidate)
}
